[instance]
#problem_instance = "/fjsp/1_Brandimarte/Mk01.fjs" # configure problem instance to be scheduled
problem_instance = "/jsp/adams/abz5" # configure problem instance to be scheduled

[solver]
time_limit = 3600 # time limit for the OR-tools CP-SAT solver, in seconds

[output]
plotting = false # draw ganttchart of found solution